"""Python bindings for MorphologicalAttributeFilters.

Preferred usage is the NodeId-based MorphologicalTree API:
- `getRoot()`
- `getAliveNodeIds`
- `getChildren`
- `getProperParts`
- `getSmallestComponent`
- `Attribute.traversePostOrder`

Python-friendly query aliases are also available:
- `tree.root`
- `tree.alive_node_ids`
- `tree.children_of(node_id)`
- `tree.parent_of(node_id)`
- `tree.proper_parts_of(node_id)`

Weighted helpers live on `WeightedMorphologicalTree`:
- `weighted.getAltitude(node_id)`
- `weighted.altitude_of(node_id)`
- `weighted.reconstructionImage()`

Convenience constructors:
- `MorphologicalTree.createMaxTree(image)`
- `MorphologicalTree.createMinTree(image)`
- `WeightedMorphologicalTree.createMaxTree(image)`
- `WeightedMorphologicalTree.createMinTree(image)`
"""

# Version (generated by setuptools-scm at build time when packaging)
try:
    from ._version import version as __version__
except ImportError:  # pragma: no cover - local CMake builds may not generate it
    __version__ = "0+unknown"

# Import native pybind11 module packaged under this package
from . import mmcfilters as _native

# Re-export native symbols at package level
MorphologicalTree = _native.MorphologicalTree
WeightedMorphologicalTree = _native.WeightedMorphologicalTree
ToSInterpolation = _native.ToSInterpolation
NodeIdSpace = _native.NodeIdSpace
AdjacencyRelation = _native.AdjacencyRelation
AttributeFilters = _native.AttributeFilters
AttributeOpeningPrimitivesFamily = _native.AttributeOpeningPrimitivesFamily
UltimateAttributeOpening = _native.UltimateAttributeOpening
Attribute = _native.Attribute
ContourComputation = _native.ContourComputation
Contours = _native.Contours
ContourRange = _native.ContourRange
ContoursIterator = _native.ContoursIterator
ExtinctionValues = _native.ExtinctionValues
DualMinMaxTreeIncrementalFilter = _native.DualMinMaxTreeIncrementalFilter
CasfComponentTrees = _native.CasfComponentTrees
CasfComponentTreesAttribute = _native.CasfComponentTreesAttribute
ComponentTreeCasf = _native.ComponentTreeCasf
ComponentTreeCasfAttribute = _native.ComponentTreeCasfAttribute

__all__ = [
    "__version__",
    "MorphologicalTree",
    "WeightedMorphologicalTree",
    "ToSInterpolation",
    "NodeIdSpace",
    "AdjacencyRelation",
    "AttributeFilters",
    "AttributeOpeningPrimitivesFamily",
    "Attribute",
    "UltimateAttributeOpening",
    "ContourComputation",
    "Contours",
    "ContourRange",
    "ContoursIterator",
    "ExtinctionValues",
    "DualMinMaxTreeIncrementalFilter",
    "CasfComponentTrees",
    "CasfComponentTreesAttribute",
    "ComponentTreeCasf",
    "ComponentTreeCasfAttribute",
]
