#pragma once

#include "HierarchySaliencyMapValidation.hpp"
#include "../../utils/RegularGridAdjacency2D.hpp"
#include "../../utils/Altitude.hpp"
#include "../../utils/Common.hpp"
#include "../MorphologicalTree.hpp"
#include "../detail/MorphologicalTreeConstructionContextQueries.hpp"
#include "../ValuedMorphologicalTree.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <functional>
#include <iterator>
#include <sstream>
#include <span>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

namespace mmcfilters {

/**
 * @brief Edge-indexed saliency map induced by a morphological hierarchy.
 *
 * The arrays are parallel: `sources[i]`, `targets[i]`, and `values[i]` describe
 * one undirected image-domain graph edge and its saliency value. The edge set is
 * generated by the forward-only half of the supplied adjacency relation, so each
 * undirected edge appears exactly once.
 */
template <class Value> struct EdgeSaliencyMap {
    /// Number of rows in the image grid.
    int numRows = 0;
    /// Number of columns in the image grid.
    int numColumns = 0;
    /// Radius of the adjacency used to enumerate the edges.
    double adjacencyRadius = 0.0;
    /// Source pixel identifier of each undirected edge.
    std::vector<NodeId> sources;
    /// Target pixel identifier of each undirected edge.
    std::vector<NodeId> targets;
    /// Saliency value parallel to `sources` and `targets`.
    std::vector<Value> values;

    /**
     * @brief Returns the number of edge values.
     *
     * @return The number of edge values.
     */
    [[nodiscard]] std::size_t size() const noexcept { return values.size(); }

    /**
     * @brief Returns whether the edge map has no values.
     *
     * @return Whether the edge map has no values.
     */
    [[nodiscard]] bool empty() const noexcept { return values.empty(); }
};

/**
 * @brief Meaning assigned to a node valuation during LCA projection.
 *
 * `EdgeSaliencyValue` means that the supplied value is already the value to be
 * written on a transition edge. `PartitionAppearanceLevel` follows Algorithm 1
 * of Cousty et al.: the value is the (positive integer) first partition level at
 * which the region appears, so the edge receives `level(LCA) - 1`.
 */
enum class HierarchyLevelConvention {
    EdgeSaliencyValue,
    PartitionAppearanceLevel,
};

/**
 * @brief Projects a morphological tree hierarchy onto an image adjacency graph.
 *
 * The generic `computeEdgeMap` primitive finds the smallest nodes of each graph
 * edge endpoint, takes their lowest common ancestor in the hierarchy, and writes
 * `nodeValue(lca)` as the edge value. The formal `computeSaliencyEdgeMap` path
 * additionally assigns the base value `0` to edges whose endpoints already
 * belong to the same finest region represented by the tree. With a connected
 * complete hierarchy and a compatible valuation, this is the `Phi(H)`
 * saliency-map representation from Cousty et al.,
 * "Hierarchical segmentations with graphs: quasi-flat zones, minimum spanning
 * trees, and saliency maps". This class implements that edge-indexed hierarchy
 * projection only; it does not build the full `Psi(w) = Phi(QFZ(G, w))`
 * pipeline from an arbitrary edge-valuedTree graph, nor the paper's MST
 * characterization.
 *
 * @par Primary reference
 * Jean Cousty, Laurent Najman, Yukiko Kenmochi, and Silvio Guimarães,
 * "Hierarchical segmentations with graphs: quasi-flat zones, minimum spanning
 * trees, and saliency maps," Journal of Mathematical Imaging and Vision,
 * 60(4):479-502, 2018.
 * [DOI 10.1007/s10851-017-0768-7](https://doi.org/10.1007/s10851-017-0768-7).
 * The direct projection corresponds to Section 4, Equations (5)-(6), and
 * Section 7, Algorithm 1.
 */
class HierarchySaliencyMap {
  private:
    /**
     * @brief Validates tree and adjacency.
     *
     * @param tree Tree topology.
     * @param adjacency Adjacency relation.
     * @param context Operation name used in diagnostics.
     */
    static void validateTreeAndAdjacency(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency, const char* context) {
        detail::requireCommittedRootedHierarchy(tree, context);
        if (tree.numRows() <= 0 || tree.numColumns() <= 0 || tree.numPixels() <= 0) {
            throw std::invalid_argument(std::string(context) + " requires a non-empty image/pixel domain.");
        }
        if (adjacency.getNumRows() != tree.numRows() || adjacency.getNumColumns() != tree.numColumns()) {
            std::ostringstream oss;
            oss << context << " adjacency domain must match the tree image domain; got " << adjacency.getNumRows() << "x" << adjacency.getNumColumns()
                << " for a tree domain of " << tree.numRows() << "x" << tree.numColumns() << ".";
            throw std::invalid_argument(oss.str());
        }
    }

    /**
     * @brief Tests whether two stored relations define the same grid graph.
     *
     * Construction metadata such as the original radius is intentionally not
     * compared: saliency projection depends on the actual immutable stencil.
     *
     * @param lhs Left-hand operand.
     * @param rhs Right-hand operand.
     * @return True if two stored relations define the same grid graph; otherwise false.
     */
    static bool sameAdjacencyGraph(const RegularGridAdjacency2D& lhs, const RegularGridAdjacency2D& rhs) noexcept {
        if (lhs.getNumRows() != rhs.getNumRows() || lhs.getNumColumns() != rhs.getNumColumns() || lhs.getSize() != rhs.getSize()) {
            return false;
        }
        for (int index = 0; index < lhs.getSize(); ++index) {
            if (lhs.getOffsetRow(index) != rhs.getOffsetRow(index) || lhs.getOffsetColumn(index) != rhs.getOffsetColumn(index)) {
                return false;
            }
        }
        return true;
    }

    /**
     * @brief Validates stored adjacency.
     *
     * @param tree Tree topology.
     * @param context Operation name used in diagnostics.
     * @return Mutable reference to the updated object.
     */
    static RegularGridAdjacency2D requireStoredAdjacency(const MorphologicalTree& tree, const char* context) {
        if (const RegularGridAdjacency2D* adjacency = ::mmcfilters::detail::constructionAdjacency(tree)) {
            return *adjacency;
        }
        if (const ComplementaryAdjacencies* adjacencies = ::mmcfilters::detail::complementaryAdjacencies(tree)) {
            if (sameAdjacencyGraph(adjacencies->minAdjacency, adjacencies->maxAdjacency)) {
                return adjacencies->minAdjacency;
            }
            throw std::invalid_argument(
                std::string(context) +
                " cannot infer one image graph from distinct minimum/maximum adjacencies; pass the intended adjacency explicitly.");
        }
        if (const TopographicConvention* convention = tree.topographicConvention();
            convention != nullptr && std::holds_alternative<SelfDualSpanImmersion>(convention->immersion) && tree.hasGridDomain2D()) {
            const GridDomain2D& domain = *tree.gridDomain2D();
            return RegularGridAdjacency2D(domain.rows, domain.columns, 1.0);
        }
        throw std::invalid_argument(std::string(context) + " requires an attached adjacency relation; pass an explicit adjacency relation instead.");
    }

  public:
    /**
     * @brief Returns the unambiguous adjacency stored by a hierarchy.
     *
     * This public query lets higher-level saliency constructions reuse exactly
     * the same graph-selection contract as the direct LCA projection.
     *
     * @param tree Tree carrying adjacency semantics.
     * @param context Operation name used in diagnostics.
     * @return Stored uniform graph, or the common graph of an equivalent
     * directional pair.
     */
    [[nodiscard]] static RegularGridAdjacency2D requireProjectionAdjacency(
        const MorphologicalTree& tree, const char* context = "HierarchySaliencyMap::requireProjectionAdjacency") {
        return requireStoredAdjacency(tree, context);
    }

    /**
     * @brief Computes a dense topological level buffer indexed by internal NodeId.
     *
     * Leaf internal nodes receive level `0`. Each other node receives one plus
     * the maximum level of its direct children. The root therefore has the
     * largest value in a connected tree, yielding a hierarchy scale that grows
     * from fine regions toward coarse regions independently of altitude
     * polarity.
     *
     * @param tree Tree topology.
     * @return The computed dense topological level buffer indexed by internal NodeId.
     */
    [[nodiscard]] static std::vector<int> computeTopologicalLevels(const MorphologicalTree& tree) {
        detail::requireCommittedRootedHierarchy(tree, "HierarchySaliencyMap::computeTopologicalLevels");

        std::vector<int> levels(static_cast<std::size_t>(tree.numInternalNodeSlots()), 0);
        for (NodeId nodeId : tree.postOrder()) {
            int level = 0;
            for (NodeId childId : tree.children(nodeId)) {
                level = std::max(level, levels[static_cast<std::size_t>(childId)] + 1);
            }
            levels[static_cast<std::size_t>(nodeId)] = level;
        }
        return levels;
    }

    /**
     * @brief Computes partition-appearance indexes for the proper-part completion.
     *
     * Direct proper-part regions form the first non-singleton partition level.
     * Consequently, these indexes are the structural saliency heights shifted by
     * one: internal leaves receive `1`, and every ancestor receives one plus the
     * maximum child appearance level.
     *
     * @param tree Tree topology.
     * @return Dense positive integer levels indexed by internal NodeId.
     */
    [[nodiscard]] static std::vector<int> computePartitionAppearanceLevels(const MorphologicalTree& tree) {
        std::vector<int> levels = computeTopologicalLevels(tree);
        for (NodeId nodeId : tree.aliveNodeIds()) {
            ++levels[static_cast<std::size_t>(nodeId)];
        }
        return levels;
    }

    /**
     * @brief Computes an edge saliency map using an explicit adjacency relation.
     *
     * `NodeValue` must be callable as `nodeValue(NodeId)` and is invoked once per
     * graph edge on the LCA of the two endpoint smallest nodes. This is the generic LCA
     * projection primitive; use `computeSaliencyEdgeMap` when arbitrary node
     * values must be validated as a formal hierarchy valuation before projection.
     *
     * @param tree Tree topology.
     * @param adjacency Adjacency relation.
     * @param nodeValue Value assigned to the node.
     * @return The computed edge saliency map using an explicit adjacency relation.
     */
    template <class NodeValue>
    [[nodiscard]] static auto computeEdgeMap(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency, NodeValue&& nodeValue)
        -> EdgeSaliencyMap<std::decay_t<std::invoke_result_t<NodeValue, NodeId>>> {
        using Value = std::decay_t<std::invoke_result_t<NodeValue, NodeId>>;
        static_assert(!std::is_void_v<Value>, "HierarchySaliencyMap nodeValue must return a value.");

        constexpr const char* context = "HierarchySaliencyMap::computeEdgeMap";
        validateTreeAndAdjacency(tree, adjacency, context);

        EdgeSaliencyMap<Value> saliency;
        saliency.numRows = tree.numRows();
        saliency.numColumns = tree.numColumns();
        saliency.adjacencyRadius = adjacency.getRadius();

        auto&& scorer = nodeValue;
        const int numPixels = tree.numPixels();
        for (NodeId source = 0; source < numPixels; ++source) {
            const NodeId sourceSmallestNode = tree.smallestNode(source);
            if (!tree.isAlive(sourceSmallestNode)) {
                throw std::runtime_error("HierarchySaliencyMap::computeEdgeMap found a pixel without a live smallest node.");
            }

            for (int target : adjacency.getForwardNeighborIndices(source)) {
                const NodeId targetSmallestNode = tree.smallestNode(target);
                if (!tree.isAlive(targetSmallestNode)) {
                    throw std::runtime_error("HierarchySaliencyMap::computeEdgeMap found a neighbour pixel without a live smallest node.");
                }

                const NodeId lca = tree.lowestCommonAncestor(sourceSmallestNode, targetSmallestNode);
                if (lca == InvalidNode || !tree.isAlive(lca)) {
                    throw std::runtime_error("HierarchySaliencyMap::computeEdgeMap could not find a live LCA for an adjacency edge.");
                }

                saliency.sources.push_back(source);
                saliency.targets.push_back(target);
                saliency.values.push_back(std::invoke(scorer, lca));
            }
        }

        return saliency;
    }

    /**
     * @brief Computes the formal edge-indexed saliency map induced by a valuation.
     *
     * This is the API that matches the saliency map `Phi(H)` defined in Cousty
     * et al., "Hierarchical segmentations with graphs: quasi-flat zones, minimum
     * spanning trees, and saliency maps": the result is a function on graph
     * edges, not a raster contour image. The input valuation is validated before
     * projection so arbitrary node valuations cannot be mislabeled as a
     * quasi-flat-zone saliency map. The caller provides `H` through the tree
     * topology; this method does not construct `QFZ(G, w)` from an arbitrary
     * edge-valuedTree graph.
     *
     * Formal saliency valuations must be non-negative because edges internal to
     * the finest represented regions use the fixed base level `0`. Use
     * `HierarchySaliencyMapValidation::rankHierarchyValuation` or
     * `computeNormalizedScores` before projection when the original compatible
     * valuation contains negative values.
     *
     * For every adjacency edge `(p, q)`, the returned value is the base level
     * `0` when both endpoints already belong to the same finest region exposed
     * by the tree. Otherwise, under `EdgeSaliencyValue` the returned value is:
     *
     *     valuation(LCA(smallestNode(p), smallestNode(q)))
     *
     * Under `PartitionAppearanceLevel`, the returned transition value is instead
     * `valuation(LCA(...)) - 1`, following Algorithm 1 of Cousty et al. In that
     * convention, live-node values must be positive integer partition indexes.
     * Here `smallestNode` maps a pixel to its smallest hierarchy node.
     * This keeps the saliency map defined on the full graph edge set while
     * respecting the paper's cut-based definition: edges internal to a finest
     * region are not contour transitions at any positive hierarchy level.
     *
     * @param tree Tree topology.
     * @param adjacency Adjacency relation.
     * @param valuation Node valuation.
     * @param policy Policy controlling the operation.
     * @param levelConvention Interpretation of live-node valuation levels.
     * @param connectivityPolicy Whether to validate connected hierarchy supports.
     * @return The computed formal edge-indexed saliency map induced by a valuation.
     */
    template <class Value>
    [[nodiscard]] static EdgeSaliencyMap<Value>
    computeSaliencyEdgeMap(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency, std::span<const Value> valuation,
                           HierarchyValuationPolicy policy = HierarchyValuationPolicy::AllowLevelCollapse,
                           HierarchyLevelConvention levelConvention = HierarchyLevelConvention::EdgeSaliencyValue,
                           HierarchyConnectivityPolicy connectivityPolicy = HierarchyConnectivityPolicy::ValidateConnected) {
        constexpr const char* context = "HierarchySaliencyMap::computeSaliencyEdgeMap";
        HierarchySaliencyMapValidation::validateHierarchyValuation(tree, valuation, policy, HierarchyValuationRangePolicy::RequireNonNegative, context);
        validateTreeAndAdjacency(tree, adjacency, context);
        if (connectivityPolicy == HierarchyConnectivityPolicy::ValidateConnected) {
            HierarchySaliencyMapValidation::validateHierarchyConnectivity(tree, adjacency, context);
        }
        if (levelConvention == HierarchyLevelConvention::PartitionAppearanceLevel) {
            for (NodeId nodeId : tree.aliveNodeIds()) {
                const Value& level = valuation[static_cast<std::size_t>(nodeId)];
                if (!(Value{} < level)) {
                    throw std::invalid_argument(std::string(context) + " requires positive partition-appearance levels.");
                }
                if constexpr (std::is_floating_point_v<Value>) {
                    if (std::floor(level) != level) {
                        throw std::invalid_argument(std::string(context) + " requires integer-valued partition-appearance levels.");
                    }
                }
            }
        }

        EdgeSaliencyMap<Value> saliency;
        saliency.numRows = tree.numRows();
        saliency.numColumns = tree.numColumns();
        saliency.adjacencyRadius = adjacency.getRadius();

        const int numPixels = tree.numPixels();
        for (NodeId source = 0; source < numPixels; ++source) {
            const NodeId sourceSmallestNode = tree.smallestNode(source);
            if (!tree.isAlive(sourceSmallestNode)) {
                throw std::runtime_error(std::string(context) + " found a pixel without a live smallest node.");
            }

            for (int target : adjacency.getForwardNeighborIndices(source)) {
                const NodeId targetSmallestNode = tree.smallestNode(target);
                if (!tree.isAlive(targetSmallestNode)) {
                    throw std::runtime_error(std::string(context) + " found a neighbour pixel without a live smallest node.");
                }

                Value edgeValue{};
                if (sourceSmallestNode != targetSmallestNode) {
                    const NodeId lca = tree.lowestCommonAncestor(sourceSmallestNode, targetSmallestNode);
                    if (lca == InvalidNode || !tree.isAlive(lca)) {
                        throw std::runtime_error(std::string(context) + " could not find a live LCA for an adjacency edge.");
                    }
                    edgeValue = valuation[static_cast<std::size_t>(lca)];
                    if (levelConvention == HierarchyLevelConvention::PartitionAppearanceLevel) {
                        edgeValue -= Value{1};
                    }
                }

                saliency.sources.push_back(source);
                saliency.targets.push_back(target);
                saliency.values.push_back(edgeValue);
            }
        }

        return saliency;
    }

    /**
     * @brief Computes a formal saliency map using one unambiguous stored graph.
     *
     * Uniform adjacency is used directly. A directional context is accepted
     * only when its decreasing and increasing relations have the same stencil;
     * otherwise the caller must select an explicit projection graph.
     *
     * @param tree Tree topology.
     * @param valuation Node valuation.
     * @param policy Policy controlling the operation.
     * @param levelConvention Interpretation of live-node valuation levels.
     * @param connectivityPolicy Whether to validate connected hierarchy supports.
     * @return The computed formal saliency map using one unambiguous stored graph.
     */
    template <class Value>
    [[nodiscard]] static EdgeSaliencyMap<Value>
    computeSaliencyEdgeMap(const MorphologicalTree& tree, std::span<const Value> valuation,
                           HierarchyValuationPolicy policy = HierarchyValuationPolicy::AllowLevelCollapse,
                           HierarchyLevelConvention levelConvention = HierarchyLevelConvention::EdgeSaliencyValue,
                           HierarchyConnectivityPolicy connectivityPolicy = HierarchyConnectivityPolicy::ValidateConnected) {
        return computeSaliencyEdgeMap(tree, requireStoredAdjacency(tree, "HierarchySaliencyMap::computeSaliencyEdgeMap"), valuation, policy, levelConvention,
                                      connectivityPolicy);
    }

    /**
     * @brief Computes the canonical dense integer saliency scale of a valuation.
     *
     * Unlike `rankHierarchyValuation`, this operation ranks only values that
     * actually occur as transition levels on graph edges. Same-smallest-node edges form
     * the base level when present. This removes unused node ranks and produces
     * the minimal dense scale associated with the completed graph hierarchy.
     * Input values may be negative because only their order is retained.
     *
     * @param tree Hierarchy topology and smallest-node mapping.
     * @param adjacency Projection graph.
     * @param valuation Finite hierarchy-compatible node valuation.
     * @param policy Whether adjacent equal hierarchy values may collapse.
     * @param connectivityPolicy Whether to verify graph connectedness.
     * @return Edge saliency map with dense values `0..k-1` over effective edges.
     */
    template <class Value>
    [[nodiscard]] static EdgeSaliencyMap<int>
    computeCanonicalRankedSaliencyEdgeMap(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency, std::span<const Value> valuation,
                                          HierarchyValuationPolicy policy = HierarchyValuationPolicy::AllowLevelCollapse,
                                          HierarchyConnectivityPolicy connectivityPolicy = HierarchyConnectivityPolicy::ValidateConnected) {
        constexpr const char* context = "HierarchySaliencyMap::computeCanonicalRankedSaliencyEdgeMap";
        HierarchySaliencyMapValidation::validateHierarchyValuation(tree, valuation, policy, HierarchyValuationRangePolicy::AllowAnyFinite, context);
        validateTreeAndAdjacency(tree, adjacency, context);
        if (connectivityPolicy == HierarchyConnectivityPolicy::ValidateConnected) {
            HierarchySaliencyMapValidation::validateHierarchyConnectivity(tree, adjacency, context);
        }

        EdgeSaliencyMap<int> saliency;
        saliency.numRows = tree.numRows();
        saliency.numColumns = tree.numColumns();
        saliency.adjacencyRadius = adjacency.getRadius();

        struct ProjectedLevel {
            NodeId source;
            NodeId target;
            NodeId lca;
        };
        std::vector<ProjectedLevel> projected;
        std::vector<Value> effectiveValues;
        bool hasBaseEdge = false;
        const int numPixels = tree.numPixels();
        for (NodeId source = 0; source < numPixels; ++source) {
            const NodeId sourceSmallestNode = tree.smallestNode(source);
            for (int targetValue : adjacency.getForwardNeighborIndices(source)) {
                const NodeId target = static_cast<NodeId>(targetValue);
                const NodeId targetSmallestNode = tree.smallestNode(target);
                NodeId lca = InvalidNode;
                if (sourceSmallestNode == targetSmallestNode) {
                    hasBaseEdge = true;
                } else {
                    lca = tree.lowestCommonAncestor(sourceSmallestNode, targetSmallestNode);
                    if (lca == InvalidNode || !tree.isAlive(lca)) {
                        throw std::runtime_error(std::string(context) + " could not find a live LCA for an adjacency edge.");
                    }
                    effectiveValues.push_back(valuation[static_cast<std::size_t>(lca)]);
                }
                projected.push_back(ProjectedLevel{source, target, lca});
            }
        }

        std::sort(effectiveValues.begin(), effectiveValues.end());
        effectiveValues.erase(std::unique(effectiveValues.begin(), effectiveValues.end()), effectiveValues.end());
        saliency.sources.reserve(projected.size());
        saliency.targets.reserve(projected.size());
        saliency.values.reserve(projected.size());
        const int transitionOffset = hasBaseEdge ? 1 : 0;
        for (const ProjectedLevel& edge : projected) {
            int rank = 0;
            if (edge.lca != InvalidNode) {
                const Value& value = valuation[static_cast<std::size_t>(edge.lca)];
                rank = transitionOffset +
                       static_cast<int>(std::distance(effectiveValues.begin(), std::lower_bound(effectiveValues.begin(), effectiveValues.end(), value)));
            }
            saliency.sources.push_back(edge.source);
            saliency.targets.push_back(edge.target);
            saliency.values.push_back(rank);
        }
        return saliency;
    }

    /**
     * @brief Stored-adjacency overload of `computeCanonicalRankedSaliencyEdgeMap`.
     *
     * @tparam Value Node-valuation scalar type.
     * @param tree Tree topology carrying one unambiguous stored projection graph.
     * @param valuation Dense valuation indexed by internal node id.
     * @param policy Whether equal parent/child hierarchy values are accepted.
     * @param connectivityPolicy Whether spatial support connectivity is validated.
     * @return Full edge map with dense ranks over effective transition values.
     */
    template <class Value>
    [[nodiscard]] static EdgeSaliencyMap<int>
    computeCanonicalRankedSaliencyEdgeMap(const MorphologicalTree& tree, std::span<const Value> valuation,
                                          HierarchyValuationPolicy policy = HierarchyValuationPolicy::AllowLevelCollapse,
                                          HierarchyConnectivityPolicy connectivityPolicy = HierarchyConnectivityPolicy::ValidateConnected) {
        return computeCanonicalRankedSaliencyEdgeMap(tree, requireStoredAdjacency(tree, "HierarchySaliencyMap::computeCanonicalRankedSaliencyEdgeMap"),
                                                     valuation, policy, connectivityPolicy);
    }

    /**
     * @brief Densely ranks the values already present in an edge saliency map.
     *
     * @tparam Value Edge-value scalar type.
     * @param edgeMap Edge map whose distinct values define the rank scale.
     * @return Copy of the edge domain with values replaced by zero-based dense
     * ranks in ascending value order.
     */
    template <class Value> [[nodiscard]] static EdgeSaliencyMap<int> rankEdgeSaliencyMap(const EdgeSaliencyMap<Value>& edgeMap) {
        EdgeSaliencyMap<int> ranked;
        ranked.numRows = edgeMap.numRows;
        ranked.numColumns = edgeMap.numColumns;
        ranked.adjacencyRadius = edgeMap.adjacencyRadius;
        ranked.sources = edgeMap.sources;
        ranked.targets = edgeMap.targets;
        std::vector<Value> uniqueValues = edgeMap.values;
        std::sort(uniqueValues.begin(), uniqueValues.end());
        uniqueValues.erase(std::unique(uniqueValues.begin(), uniqueValues.end()), uniqueValues.end());
        ranked.values.reserve(edgeMap.values.size());
        for (const Value& value : edgeMap.values) {
            ranked.values.push_back(static_cast<int>(std::distance(uniqueValues.begin(), std::lower_bound(uniqueValues.begin(), uniqueValues.end(), value))));
        }
        return ranked;
    }

    /**
     * @brief Computes an edge saliency map using one unambiguous stored graph.
     *
     * @param tree Tree topology.
     * @param nodeValue Value assigned to the node.
     * @return The computed edge saliency map using one unambiguous stored graph.
     */
    template <class NodeValue>
    [[nodiscard]] static auto computeEdgeMap(const MorphologicalTree& tree, NodeValue&& nodeValue)
        -> EdgeSaliencyMap<std::decay_t<std::invoke_result_t<NodeValue, NodeId>>> {
        return computeEdgeMap(tree, requireStoredAdjacency(tree, "HierarchySaliencyMap::computeEdgeMap"), std::forward<NodeValue>(nodeValue));
    }

    /**
     * @brief Computes a topological-level edge saliency map with explicit adjacency.
     *
     * @param tree Tree topology.
     * @param adjacency Adjacency relation.
     * @return The computed topological-level edge saliency map with explicit adjacency.
     */
    [[nodiscard]] static EdgeSaliencyMap<int> computeTopologicalLevelEdgeMap(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency) {
        std::vector<int> levels = computeTopologicalLevels(tree);
        return computeCanonicalRankedSaliencyEdgeMap(tree, adjacency, std::span<const int>(levels), HierarchyValuationPolicy::RequireStrictHierarchy);
    }

    /**
     * @brief Computes a topological-level map using one unambiguous stored graph.
     *
     * @param tree Tree topology.
     * @return The computed topological-level map using one unambiguous stored graph.
     */
    [[nodiscard]] static EdgeSaliencyMap<int> computeTopologicalLevelEdgeMap(const MorphologicalTree& tree) {
        return computeTopologicalLevelEdgeMap(tree, requireStoredAdjacency(tree, "HierarchySaliencyMap::computeTopologicalLevelEdgeMap"));
    }

    /**
     * @brief Computes a normalized-altitude edge saliency map with explicit adjacency.
     *
     * @param tree Tree topology.
     * @param adjacency Adjacency relation.
     * @return The computed normalized-altitude edge saliency map with explicit adjacency.
     */
    template <AltitudeValue T>
    [[nodiscard]] static EdgeSaliencyMap<double> computeNormalizedAltitudeEdgeMap(const ValuedMorphologicalTree<T>& tree,
                                                                                  const RegularGridAdjacency2D& adjacency) {
        std::vector<double> scores = HierarchySaliencyMapValidation::computeNormalizedScores(tree);
        return computeSaliencyEdgeMap(tree.topology(), adjacency, std::span<const double>(scores), HierarchyValuationPolicy::AllowLevelCollapse);
    }

    /**
     * @brief Computes a normalized-altitude map using one unambiguous stored graph.
     *
     * @param tree Tree topology.
     * @return The computed normalized-altitude map using one unambiguous stored graph.
     */
    template <AltitudeValue T> [[nodiscard]] static EdgeSaliencyMap<double> computeNormalizedAltitudeEdgeMap(const ValuedMorphologicalTree<T>& tree) {
        return computeNormalizedAltitudeEdgeMap(tree, requireStoredAdjacency(tree.topology(), "HierarchySaliencyMap::computeNormalizedAltitudeEdgeMap"));
    }
};

/**
 * @brief Explicit proper-part completion of a morphological component tree.
 *
 * A component tree is a hierarchy of partial partitions, whereas Cousty's
 * saliency correspondence uses complete connected partitions of the graph
 * domain. This adapter states the completion used by this library:
 *
 * - partition 0 contains graph-vertex singletons;
 * - zero-valued same-smallest-node edges form the connected atoms of direct proper
 *   parts;
 * - component-tree nodes merge those atoms and their child supports;
 * - every resulting node support must be connected in the selected graph.
 *
 * The adapter is a semantic facade over `HierarchySaliencyMap`; it does not
 * copy or rewrite the component-tree topology.
 */
class ComponentTreePartitionHierarchyAdapter {
  public:
    /**
     * @brief Validates the connected complete-partition interpretation.
     *
     * @param tree Component-tree topology to validate.
     * @param adjacency Projection graph on the tree pixel domain.
     * @throws std::invalid_argument If the graph domain is incompatible or a
     * hierarchy support is disconnected.
     */
    static void validate(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency) {
        HierarchySaliencyMapValidation::validateHierarchyConnectivity(tree, adjacency, "ComponentTreePartitionHierarchyAdapter::validate");
    }

    /**
     * @brief Returns the structural partition-appearance levels of the completion.
     *
     * @param tree Component-tree topology whose completion is ranked.
     * @return Dense internal-node-id buffer of positive appearance levels.
     */
    [[nodiscard]] static std::vector<int> computePartitionAppearanceLevels(const MorphologicalTree& tree) {
        return HierarchySaliencyMap::computePartitionAppearanceLevels(tree);
    }

    /**
     * @brief Projects explicit partition-appearance levels with `level(LCA)-1`.
     *
     * @tparam Value Partition-level scalar type.
     * @param tree Component-tree topology to complete and project.
     * @param adjacency Projection graph on the pixel domain.
     * @param partitionAppearanceLevels Dense positive level per internal node id.
     * @param policy Whether equal parent/child appearance levels are accepted.
     * @return Full edge-indexed saliency map on `adjacency`.
     * @throws std::invalid_argument If the hierarchy, graph, valuation, or support
     * connectivity contract is invalid.
     */
    template <class Value>
    [[nodiscard]] static EdgeSaliencyMap<Value> computeSaliencyEdgeMap(const MorphologicalTree& tree, const RegularGridAdjacency2D& adjacency,
                                                                       std::span<const Value> partitionAppearanceLevels,
                                                                       HierarchyValuationPolicy policy = HierarchyValuationPolicy::AllowLevelCollapse) {
        return HierarchySaliencyMap::computeSaliencyEdgeMap(tree, adjacency, partitionAppearanceLevels, policy,
                                                            HierarchyLevelConvention::PartitionAppearanceLevel, HierarchyConnectivityPolicy::ValidateConnected);
    }
};

} // namespace mmcfilters
