#pragma once

#include "BitquadAttributeData.hpp"
#include "../../../localEvents/EventEngine.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace mmcfilters::attributes::computers::detail {

/**
 * @brief Bitquad family counters computed through local entry-event deltas.
 *
 * @details
 * This class owns the canonical local-event representation for bitquad
 * attributes. Local 2x2 state changes are first projected as per-node deltas;
 * final per-node counters are obtained by bottom-up aggregation of those
 * deltas. Scalar `BITQUADS_*` attributes are materialized from the aggregated
 * family counters by
 * `attributes::computers::BitquadAttributeComputer`.
 *
 * The binary cell is evaluated on the framed grid of 2x2 windows whose
 * top-left corner ranges from `(-1, -1)` to `(rows - 1, cols - 1)`. A state is
 * encoded with four bits:
 *
 * - bit 0: top-left sample;
 * - bit 1: bottom-left sample;
 * - bit 2: top-right sample;
 * - bit 3: bottom-right sample.
 *
 * Non-empty states are produced by four anchor placements. The lowest visible
 * bit owns the cell, so each non-empty 2x2 configuration is counted exactly
 * once. The empty state is not generated by local events; it is filled as the
 * complement of the framed 2x2 grid after all non-empty states are known.
 *
 * The family-delta path is the canonical internal compact representation used
 * for scalar descriptors. The 16-state histogram path remains available for
 * state-level inspection and export comparisons.
 */
class BitquadLocalEventComputation {
  public:
    /**
     * @brief Counts the 16 binary configurations of a framed 2x2 cell.
     */
    using BitquadStateHistogram = std::array<int, 16>;

    /**
     * @brief Reused event-engine window offset type.
     */
    using WindowOffset = local_events::WindowOffset;

    /**
     * @brief Canonical family assigned to one 2x2 state.
     */
    enum class StateFamily : uint8_t { Empty, Q1, Q2, QD, Q3, Q4 };

    /** @brief Defines the `BitquadFamilyCounts` alias used by the component. */
    using BitquadFamilyCounts = ::mmcfilters::attributes::computers::detail::BitquadFamilyCounts;

  private:
    /**
     * @brief Policy that accumulates projected family counters directly.
     *
     * @details
     * The policy accepts only states owned by its `anchorBit`, which is the
     * lowest visible bit of the 2x2 cell. A transition removes the previous
     * owned state's family and adds the new owned state's family, allowing the
     * generic event engine to store only local deltas before subtree merging.
     */
    struct BitquadFamilyCountPolicy {
        /** @brief Defines the `Bucket` alias used by the component. */
        using Bucket = BitquadFamilyCounts;

        /** @brief Stores the anchor bit. */
        uint32_t anchorBit = 0;

        /**
         * @brief Constructs `BitquadFamilyCountPolicy` from the supplied inputs.
         *
         * @param anchorBit Bit mask identifying the anchor sample in a local configuration.
         */
        explicit BitquadFamilyCountPolicy(uint32_t anchorBit) : anchorBit(anchorBit) {}

        /**
         * @brief Initializes an accumulator from a local bitquad state.
         *
         * @param bucket Accumulator updated by the operation.
         * @param state State read or updated by the operation.
         */
        void applyInitial(Bucket& bucket, uint32_t state) const { addOwnedState(bucket, state, 1); }

        /**
         * @brief Applies transition.
         *
         * @param bucket Accumulator updated by the operation.
         * @param oldState State before the transition.
         * @param newState State after the transition.
         */
        void applyTransition(Bucket& bucket, uint32_t oldState, uint32_t newState) const {
            addOwnedState(bucket, oldState, -1);
            addOwnedState(bucket, newState, 1);
        }

        /**
         * @brief Merges a child bitquad accumulator into its parent.
         *
         * @param parent Parent accumulator or node.
         * @param child Child accumulator or node.
         */
        void merge(Bucket& parent, const Bucket& child) const {
            parent.empty += child.empty;
            parent.q1 += child.q1;
            parent.q2 += child.q2;
            parent.qd += child.qd;
            parent.q3 += child.q3;
            parent.q4 += child.q4;
        }

      private:
        /**
         * @brief Checks whether this partition owns the supplied local bitquad state.
         *
         * @param state State read or updated by the operation.
         * @return True when the documented condition holds; otherwise false.
         */
        bool ownsState(uint32_t state) const {
            const uint32_t anchorMask = uint32_t{1} << anchorBit;
            const uint32_t lowerBitsMask = anchorMask - uint32_t{1};
            return (state & anchorMask) != 0 && (state & lowerBitsMask) == 0;
        }

        /**
         * @brief Accumulates a local bitquad state owned by this partition.
         *
         * @param bucket Accumulator updated by the operation.
         * @param state State read or updated by the operation.
         * @param delta Delta offset used by the operation.
         */
        void addOwnedState(Bucket& bucket, uint32_t state, int delta) const {
            if (!ownsState(state)) {
                return;
            }

            switch (stateFamily(state)) {
            case StateFamily::Empty:
                bucket.empty += delta;
                break;
            case StateFamily::Q1:
                bucket.q1 += delta;
                break;
            case StateFamily::Q2:
                bucket.q2 += delta;
                break;
            case StateFamily::QD:
                bucket.qd += delta;
                break;
            case StateFamily::Q3:
                bucket.q3 += delta;
                break;
            case StateFamily::Q4:
                bucket.q4 += delta;
                break;
            }
        }
    };

    /**
     * @brief Policy that accumulates the full 16-state bitquad histogram.
     */
    struct BitquadStateHistogramPolicy {
        /** @brief Defines the `Bucket` alias used by the component. */
        using Bucket = BitquadStateHistogram;

        /** @brief Stores the anchor bit. */
        uint32_t anchorBit = 0;

        /**
         * @brief Constructs `BitquadStateHistogramPolicy` from the supplied inputs.
         *
         * @param anchorBit Bit mask identifying the anchor sample in a local configuration.
         */
        explicit BitquadStateHistogramPolicy(uint32_t anchorBit) : anchorBit(anchorBit) {}

        /**
         * @brief Initializes an accumulator from a local bitquad state.
         *
         * @param bucket Accumulator updated by the operation.
         * @param state State read or updated by the operation.
         */
        void applyInitial(Bucket& bucket, uint32_t state) const { addOwnedState(bucket, state); }

        /**
         * @brief Applies transition.
         *
         * @param bucket Accumulator updated by the operation.
         * @param oldState State before the transition.
         * @param newState State after the transition.
         */
        void applyTransition(Bucket& bucket, uint32_t oldState, uint32_t newState) const {
            if (ownsState(oldState)) {
                bucket[histogramIndex(oldState)] -= 1;
            }
            addOwnedState(bucket, newState);
        }

        /**
         * @brief Checks whether this partition owns the supplied local bitquad state.
         *
         * @param state State read or updated by the operation.
         * @return True when the documented condition holds; otherwise false.
         */
        bool ownsState(uint32_t state) const {
            const uint32_t anchorMask = uint32_t{1} << anchorBit;
            const uint32_t lowerBitsMask = anchorMask - uint32_t{1};
            return (state & anchorMask) != 0 && (state & lowerBitsMask) == 0;
        }

        /**
         * @brief Accumulates a local bitquad state owned by this partition.
         *
         * @param bucket Accumulator updated by the operation.
         * @param state State read or updated by the operation.
         */
        void addOwnedState(Bucket& bucket, uint32_t state) const {
            if (ownsState(state)) {
                bucket[histogramIndex(state)] += 1;
            }
        }

        /**
         * @brief Merges a child bitquad accumulator into its parent.
         *
         * @param parent Parent accumulator or node.
         * @param child Child accumulator or node.
         */
        void merge(Bucket& parent, const Bucket& child) const {
            for (std::size_t i = 0; i < parent.size(); ++i) {
                parent[i] += child[i];
            }
        }

      private:
        /**
         * @brief Maps a local bitquad state to its histogram bin.
         *
         * @param state State read or updated by the operation.
         * @return Histogram-bin index encoded by the local state.
         */
        static std::size_t histogramIndex(uint32_t state) { return static_cast<std::size_t>(state & uint32_t{0b1111}); }
    };

  public:
    /**
     * @brief Computes and stores both state histograms and projected families.
     *
     * @param tree Tree topology used by the operation.
     */
    explicit BitquadLocalEventComputation(const MorphologicalTree& tree)
        : bitquadStateHistograms_(computeBitquadStateHistograms(tree)), bitquadFamilyCounts_(computeBitquadFamilyCounts(bitquadStateHistograms_)) {}

    /**
     * @brief Returns per-node 16-state histograms in dense internal node space.
     *
     * @return Per-node 16-state histograms in dense internal node space.
     */
    [[nodiscard]] const std::vector<BitquadStateHistogram>& getBitquadStateHistograms() const noexcept { return bitquadStateHistograms_; }

    /**
     * @brief Returns per-node projected family counters.
     *
     * @return Per-node projected family counters.
     */
    [[nodiscard]] const std::vector<BitquadFamilyCounts>& getBitquadFamilyCounts() const noexcept { return bitquadFamilyCounts_; }

    /**
     * @brief Returns the compile-time map from 2x2 state to family.
     *
     * @return The compile-time map from 2x2 state to family.
     */
    static constexpr std::array<StateFamily, 16> stateFamilyTable() noexcept {
        return {{
            StateFamily::Empty, // 0000
            StateFamily::Q1,    // 0001
            StateFamily::Q1,    // 0010
            StateFamily::Q2,    // 0011
            StateFamily::Q1,    // 0100
            StateFamily::Q2,    // 0101
            StateFamily::QD,    // 0110
            StateFamily::Q3,    // 0111
            StateFamily::Q1,    // 1000
            StateFamily::QD,    // 1001
            StateFamily::Q2,    // 1010
            StateFamily::Q3,    // 1011
            StateFamily::Q2,    // 1100
            StateFamily::Q3,    // 1101
            StateFamily::Q3,    // 1110
            StateFamily::Q4,    // 1111
        }};
    }

    /**
     * @brief Returns the family of a state in `[0, 15]`.
     *
     * @param state State read or updated by the operation.
     * @return The family of a state in [0, 15].
     */
    static constexpr StateFamily stateFamily(uint32_t state) {
        if (state > 15) {
            throw std::out_of_range("Bitquad state must be in [0, 15].");
        }
        return stateFamilyTable()[static_cast<std::size_t>(state)];
    }

    /**
     * @brief Computes full 16-state bitquad histograms for every live node.
     *
     * @details
     * The computation runs one local-event pass per possible anchor bit. Each
     * pass owns only cells whose lowest visible bit equals that anchor bit. The
     * empty state is filled afterwards as the framed-grid complement.
     *
     * @param tree Tree topology used by the operation.
     * @return The computed full 16-state bitquad histograms for every live node.
     */
    [[nodiscard]] static std::vector<BitquadStateHistogram> computeBitquadStateHistograms(const MorphologicalTree& tree) {
        std::vector<BitquadStateHistogram> histograms(static_cast<std::size_t>(tree.getNumInternalNodeSlots()));

        for (std::size_t anchorBit = 0; anchorBit < 4; ++anchorBit) {
            auto partial = local_events::EventEngine::computeWithPolicy(tree, bitquadWindowForAnchorBit(anchorBit),
                                                                        BitquadStateHistogramPolicy{static_cast<uint32_t>(anchorBit)});

            for (std::size_t node = 0; node < histograms.size(); ++node) {
                for (std::size_t state = 0; state < histograms[node].size(); ++state) {
                    histograms[node][state] += partial[node][state];
                }
            }
        }

        fillEmptyBitquadStateCounts(tree, histograms);
        return histograms;
    }

    /**
     * @brief Computes per-node 16-state bitquad deltas before subtree merging.
     *
     * @details
     * This exposes the state-level delta representation used by the event
     * model: local state changes are projected onto the first tree node where
     * they become visible, and final per-node counts are obtained by aggregating
     * child deltas into their parents. State `0000` is intentionally left at
     * zero here because empty cells are materialized as a complement only after
     * non-empty states have been aggregated.
     *
     * @param tree Tree topology used by the operation.
     * @return The computed per-node 16-state bitquad deltas before subtree merging.
     */
    [[nodiscard]] static std::vector<BitquadStateHistogram> computeBitquadStateHistogramDeltas(const MorphologicalTree& tree) {
        std::vector<BitquadStateHistogram> deltas(static_cast<std::size_t>(tree.getNumInternalNodeSlots()));

        for (std::size_t anchorBit = 0; anchorBit < 4; ++anchorBit) {
            auto partial = local_events::EventEngine::computeDeltasWithPolicy(tree, bitquadWindowForAnchorBit(anchorBit),
                                                                              BitquadStateHistogramPolicy{static_cast<uint32_t>(anchorBit)});

            for (std::size_t node = 0; node < deltas.size(); ++node) {
                for (std::size_t state = 0; state < deltas[node].size(); ++state) {
                    deltas[node][state] += partial[node][state];
                }
            }
        }

        return deltas;
    }

    /**
     * @brief Aggregates bitquad state deltas into final per-node histograms.
     *
     * @param tree Tree topology used by the operation.
     * @param deltas Delta offsets used by the operation.
     * @return Values produced by the operation.
     */
    [[nodiscard]] static std::vector<BitquadStateHistogram> aggregateBitquadStateHistogramDeltas(const MorphologicalTree& tree,
                                                                                                 std::span<const BitquadStateHistogram> deltas) {
        requireStateHistogramShape(tree, deltas, "Bitquad state delta aggregation");
        std::vector<BitquadStateHistogram> aggregated(deltas.begin(), deltas.end());
        aggregateSubtreeValues(tree, aggregated, [](BitquadStateHistogram& parent, const BitquadStateHistogram& child) {
            for (std::size_t state = 0; state < parent.size(); ++state) {
                parent[state] += child[state];
            }
        });
        fillEmptyBitquadStateCounts(tree, aggregated);
        return aggregated;
    }

    /**
     * @brief Projects one 16-state histogram into six family counters.
     *
     * @param histogram Histogram read or updated by the operation.
     * @return The projected one 16-state histogram into six family counters.
     */
    [[nodiscard]] static BitquadFamilyCounts projectBitquadFamilyCounts(const BitquadStateHistogram& histogram) {
        BitquadFamilyCounts counts;
        const auto families = stateFamilyTable();
        for (std::size_t state = 0; state < histogram.size(); ++state) {
            switch (families[state]) {
            case StateFamily::Empty:
                counts.empty += histogram[state];
                break;
            case StateFamily::Q1:
                counts.q1 += histogram[state];
                break;
            case StateFamily::Q2:
                counts.q2 += histogram[state];
                break;
            case StateFamily::QD:
                counts.qd += histogram[state];
                break;
            case StateFamily::Q3:
                counts.q3 += histogram[state];
                break;
            case StateFamily::Q4:
                counts.q4 += histogram[state];
                break;
            }
        }
        return counts;
    }

    /**
     * @brief Projects a buffer of state histograms into family counters.
     *
     * @param histograms Per-node histograms used by the operation.
     * @return The projected buffer of state histograms into family counters.
     */
    [[nodiscard]] static std::vector<BitquadFamilyCounts> computeBitquadFamilyCounts(std::span<const BitquadStateHistogram> histograms) {
        std::vector<BitquadFamilyCounts> counts;
        counts.reserve(histograms.size());
        for (const BitquadStateHistogram& histogram : histograms) {
            counts.push_back(projectBitquadFamilyCounts(histogram));
        }
        return counts;
    }

    /**
     * @brief Computes bitquad family counters through the family-delta route.
     *
     * @details
     * This is the preferred path for scalar bitquad attributes: first compute
     * the projected family deltas, then aggregate them bottom-up and fill the
     * empty family as the framed-grid complement.
     *
     * @param tree Tree topology used by the operation.
     * @return The computed bitquad family counters through the family-delta route.
     */
    [[nodiscard]] static std::vector<BitquadFamilyCounts> computeBitquadFamilyCounts(const MorphologicalTree& tree) {
        return aggregateBitquadFamilyDeltas(tree, computeBitquadFamilyDeltas(tree));
    }

    /**
     * @brief Computes projected bitquad-family deltas before subtree merging.
     *
     * @details
     * The `q1`, `q2`, `qd`, `q3`, and `q4` fields may be negative because a
     * later local state removes the previous state's contribution at the entry
     * node where the transition occurs. The `empty` field is left at zero for
     * the same reason as the state-delta path: empty cells are computed as a
     * complement after aggregation.
     *
     * @param tree Tree topology used by the operation.
     * @return The computed projected bitquad-family deltas before subtree merging.
     */
    [[nodiscard]] static std::vector<BitquadFamilyCounts> computeBitquadFamilyDeltas(const MorphologicalTree& tree) {
        std::vector<BitquadFamilyCounts> deltas(static_cast<std::size_t>(tree.getNumInternalNodeSlots()));

        for (std::size_t anchorBit = 0; anchorBit < 4; ++anchorBit) {
            auto partial = local_events::EventEngine::computeDeltasWithPolicy(tree, bitquadWindowForAnchorBit(anchorBit),
                                                                              BitquadFamilyCountPolicy{static_cast<uint32_t>(anchorBit)});

            for (std::size_t node = 0; node < deltas.size(); ++node) {
                deltas[node].q1 += partial[node].q1;
                deltas[node].q2 += partial[node].q2;
                deltas[node].qd += partial[node].qd;
                deltas[node].q3 += partial[node].q3;
                deltas[node].q4 += partial[node].q4;
            }
        }

        return deltas;
    }

    /**
     * @brief Aggregates bitquad-family deltas into final per-node counts.
     *
     * @param tree Tree topology used by the operation.
     * @param deltas Delta offsets used by the operation.
     * @return Values produced by the operation.
     */
    [[nodiscard]] static std::vector<BitquadFamilyCounts> aggregateBitquadFamilyDeltas(const MorphologicalTree& tree,
                                                                                       std::span<const BitquadFamilyCounts> deltas) {
        requireFamilyCountShape(tree, deltas, "Bitquad family delta aggregation");
        std::vector<BitquadFamilyCounts> aggregated(deltas.begin(), deltas.end());
        aggregateSubtreeValues(tree, aggregated, [](BitquadFamilyCounts& parent, const BitquadFamilyCounts& child) {
            parent.empty += child.empty;
            parent.q1 += child.q1;
            parent.q2 += child.q2;
            parent.qd += child.qd;
            parent.q3 += child.q3;
            parent.q4 += child.q4;
        });
        fillEmptyBitquadFamilyCounts(tree, aggregated);
        return aggregated;
    }

    /**
     * @brief Projects per-node state histograms onto direct proper parts.
     *
     * @details
     * Each proper part receives the histogram stored at its direct owner node.
     * This layout is useful when comparing node-space buffers against
     * implementations that report values in the image/proper-part domain.
     *
     * @param tree Tree topology used by the operation.
     * @param nodeHistograms Per-node histograms indexed by node identifier.
     * @return The projected per-node state histograms onto direct proper parts.
     */
    [[nodiscard]] static std::vector<BitquadStateHistogram> projectBitquadStateHistogramsToProperParts(const MorphologicalTree& tree,
                                                                                                       std::span<const BitquadStateHistogram> nodeHistograms) {
        requireStateHistogramShape(tree, nodeHistograms, "Bitquad state proper-part projection");
        std::vector<BitquadStateHistogram> projected(static_cast<std::size_t>(tree.getNumTotalProperParts()));
        for (NodeId properPart = 0; properPart < tree.getNumTotalProperParts(); ++properPart) {
            const NodeId owner = tree.getProperPartOwner(properPart);
            if (owner == InvalidNode || !tree.isAlive(owner)) {
                throw std::runtime_error("Bitquad state proper-part projection found a proper part without an alive owner.");
            }
            projected[static_cast<std::size_t>(properPart)] = nodeHistograms[static_cast<std::size_t>(owner)];
        }
        return projected;
    }

    /**
     * @brief Projects per-node bitquad-family counts onto direct proper parts.
     *
     * @param tree Tree topology used by the operation.
     * @param nodeCounts Per-node sample counts.
     * @return The projected per-node bitquad-family counts onto direct proper parts.
     */
    [[nodiscard]] static std::vector<BitquadFamilyCounts> projectBitquadFamilyCountsToProperParts(const MorphologicalTree& tree,
                                                                                                  std::span<const BitquadFamilyCounts> nodeCounts) {
        requireFamilyCountShape(tree, nodeCounts, "Bitquad family proper-part projection");
        std::vector<BitquadFamilyCounts> projected(static_cast<std::size_t>(tree.getNumTotalProperParts()));
        for (NodeId properPart = 0; properPart < tree.getNumTotalProperParts(); ++properPart) {
            const NodeId owner = tree.getProperPartOwner(properPart);
            if (owner == InvalidNode || !tree.isAlive(owner)) {
                throw std::runtime_error("Bitquad family proper-part projection found a proper part without an alive owner.");
            }
            projected[static_cast<std::size_t>(properPart)] = nodeCounts[static_cast<std::size_t>(owner)];
        }
        return projected;
    }

    /**
     * @brief Returns the event-engine window for a chosen owner anchor bit.
     *
     * @details
     * The returned offsets position the same physical 2x2 cell around the
     * current anchor pixel. Running all four anchor placements covers every
     * non-empty cell exactly once through the lowest-visible-bit ownership rule.
     *
     * @param anchorBit Bit identifying the anchor sample in a local state.
     * @return The event-engine window for a chosen owner anchor bit.
     */
    [[nodiscard]] static std::vector<WindowOffset> bitquadWindowForAnchorBit(std::size_t anchorBit) {
        switch (anchorBit) {
        case 0:
            return {{0, 0}, {1, 0}, {0, 1}, {1, 1}};
        case 1:
            return {{-1, 0}, {0, 0}, {-1, 1}, {0, 1}};
        case 2:
            return {{0, -1}, {1, -1}, {0, 0}, {1, 0}};
        case 3:
            return {{-1, -1}, {0, -1}, {-1, 0}, {0, 0}};
        default:
            throw std::out_of_range("Bitquad anchor bit must be in [0, 3].");
        }
    }

  private:
    /**
     * @brief Validates state histogram shape.
     *
     * @param tree Tree topology used by the operation.
     * @param histograms Per-node histograms to aggregate.
     * @param context Operation name used in diagnostics.
     */
    static void requireStateHistogramShape(const MorphologicalTree& tree, std::span<const BitquadStateHistogram> histograms, const char* context) {
        if (histograms.size() < static_cast<std::size_t>(tree.getNumInternalNodeSlots())) {
            throw std::invalid_argument(std::string(context) + " requires one entry per internal node slot.");
        }
    }

    /**
     * @brief Validates family count shape.
     *
     * @param tree Tree topology used by the operation.
     * @param counts Per-node sample counts to aggregate.
     * @param context Operation name used in diagnostics.
     */
    static void requireFamilyCountShape(const MorphologicalTree& tree, std::span<const BitquadFamilyCounts> counts, const char* context) {
        if (counts.size() < static_cast<std::size_t>(tree.getNumInternalNodeSlots())) {
            throw std::invalid_argument(std::string(context) + " requires one entry per internal node slot.");
        }
    }

    /**
     * @brief Aggregates child values into their parents in post-order.
     *
     * @param tree Tree topology used by the operation.
     * @param values Values read or written by the operation.
     * @param merge Callable that merges a child value into its parent value.
     */
    template <class Value, class Merge> static void aggregateSubtreeValues(const MorphologicalTree& tree, std::vector<Value>& values, Merge merge) {
        std::vector<std::pair<NodeId, bool>> stack;
        stack.emplace_back(tree.getRoot(), false);

        while (!stack.empty()) {
            const auto [node, expanded] = stack.back();
            stack.pop_back();
            if (!expanded) {
                stack.emplace_back(node, true);
                for (NodeId child : tree.getChildren(node)) {
                    stack.emplace_back(child, false);
                }
                continue;
            }

            for (NodeId child : tree.getChildren(node)) {
                merge(values[static_cast<std::size_t>(node)], values[static_cast<std::size_t>(child)]);
            }
        }
    }

    /**
     * @brief Fills state `0000` as the complement of non-empty histogram states.
     *
     * @param tree Tree topology used by the operation.
     * @param histograms Per-node histograms used by the operation.
     */
    static void fillEmptyBitquadStateCounts(const MorphologicalTree& tree, std::vector<BitquadStateHistogram>& histograms) {
        const int totalCells = (tree.getNumRowsOfGridDomain2D() + 1) * (tree.getNumColsOfGridDomain2D() + 1);
        for (NodeId nodeId : tree.getAliveNodeIds()) {
            auto& histogram = histograms[static_cast<std::size_t>(nodeId)];
            int nonEmptyCells = 0;
            for (std::size_t state = 1; state < histogram.size(); ++state) {
                nonEmptyCells += histogram[state];
            }
            histogram[0] = totalCells - nonEmptyCells;
        }
    }

    /**
     * @brief Fills the empty family as the complement of non-empty families.
     *
     * @param tree Tree topology used by the operation.
     * @param familyCounts Per-node counters for the attribute family.
     */
    static void fillEmptyBitquadFamilyCounts(const MorphologicalTree& tree, std::vector<BitquadFamilyCounts>& familyCounts) {
        const int totalCells = (tree.getNumRowsOfGridDomain2D() + 1) * (tree.getNumColsOfGridDomain2D() + 1);
        for (NodeId nodeId : tree.getAliveNodeIds()) {
            BitquadFamilyCounts& counts = familyCounts[static_cast<std::size_t>(nodeId)];
            const int nonEmptyCells = counts.q1 + counts.q2 + counts.qd + counts.q3 + counts.q4;
            counts.empty = totalCells - nonEmptyCells;
        }
    }

    /// Cached 16-state histograms.
    std::vector<BitquadStateHistogram> bitquadStateHistograms_;
    /// Cached projected family counters.
    std::vector<BitquadFamilyCounts> bitquadFamilyCounts_;
};

} // namespace mmcfilters::attributes::computers::detail
